window.languageCatalog = {
  english: {
    name: 'English',
    script: 'Latin',
    tagline: 'Modern Latin typefaces for web and product design.',
    description: 'Browse a curated English font library built for interfaces, editorial layouts, and brand systems.',
    sample: 'The quick brown fox jumps over the lazy dog.',
    fonts: [
      { name: 'Roboto', category: 'sans-serif', style: 'Text', popularity: 10, pairing: 'Merriweather' },
      { name: 'Open Sans', category: 'sans-serif', style: 'Text', popularity: 9, pairing: 'Lora' },
      { name: 'Lato', category: 'sans-serif', style: 'Text', popularity: 9, pairing: 'Playfair Display' },
      { name: 'Montserrat', category: 'sans-serif', style: 'Display', popularity: 8, pairing: 'Source Serif Pro' },
      { name: 'Poppins', category: 'sans-serif', style: 'Text', popularity: 8, pairing: 'Merriweather' },
      { name: 'Nunito', category: 'sans-serif', style: 'Text', popularity: 7, pairing: 'PT Serif' },
      { name: 'Merriweather', category: 'serif', style: 'Text', popularity: 8, pairing: 'Roboto' },
      { name: 'Playfair Display', category: 'serif', style: 'Display', popularity: 8, pairing: 'Lato' },
      { name: 'Lora', category: 'serif', style: 'Text', popularity: 7, pairing: 'Open Sans' },
      { name: 'PT Serif', category: 'serif', style: 'Text', popularity: 6, pairing: 'Nunito' },
      { name: 'Bitter', category: 'serif', style: 'Text', popularity: 6, pairing: 'Source Sans 3' },
      { name: 'Oswald', category: 'display', style: 'Display', popularity: 8, pairing: 'Lora' },
      { name: 'Bebas Neue', category: 'display', style: 'Display', popularity: 7, pairing: 'Roboto' },
      { name: 'Anton', category: 'display', style: 'Display', popularity: 7, pairing: 'Open Sans' },
      { name: 'Abril Fatface', category: 'display', style: 'Display', popularity: 6, pairing: 'Montserrat' },
      { name: 'Pacifico', category: 'handwriting', style: 'Handwriting', popularity: 6, pairing: 'Poppins' },
      { name: 'Dancing Script', category: 'handwriting', style: 'Handwriting', popularity: 7, pairing: 'Roboto' },
      { name: 'Caveat', category: 'handwriting', style: 'Handwriting', popularity: 6, pairing: 'Lato' },
      { name: 'Fira Code', category: 'monospace', style: 'Monospace', popularity: 7, pairing: 'Inter' },
      { name: 'Source Code Pro', category: 'monospace', style: 'Monospace', popularity: 6, pairing: 'Merriweather' },
      { name: 'JetBrains Mono', category: 'monospace', style: 'Monospace', popularity: 7, pairing: 'Poppins' },
      { name: 'Inconsolata', category: 'monospace', style: 'Monospace', popularity: 5, pairing: 'Lora' },
      { name: 'Inter', category: 'sans-serif', style: 'Text', popularity: 9, pairing: 'Merriweather' },
      { name: 'Raleway', category: 'sans-serif', style: 'Display', popularity: 8, pairing: 'Playfair Display' },
      { name: 'Work Sans', category: 'sans-serif', style: 'Text', popularity: 8, pairing: 'Lora' },
      { name: 'Source Sans 3', category: 'sans-serif', style: 'Text', popularity: 7, pairing: 'Bitter' },
      { name: 'Ubuntu', category: 'sans-serif', style: 'Text', popularity: 7, pairing: 'PT Serif' },
      { name: 'Nunito Sans', category: 'sans-serif', style: 'Text', popularity: 7, pairing: 'Playfair Display' },
      { name: 'Noto Sans', category: 'sans-serif', style: 'Text', popularity: 7, pairing: 'Noto Serif' },
      { name: 'Rubik', category: 'sans-serif', style: 'Text', popularity: 6, pairing: 'Crimson Pro' }
    ]
  },
  telugu: {
    name: 'Telugu',
    script: 'Telugu',
    tagline: 'Contemporary Telugu typefaces for digital content and publishing.',
    description: 'Discover Telugu fonts tailored for UI, headlines, and long-form reading.',
    sample: 'తెలుగు భాషలో ఒక నమూనా వాక్యం.',
    fonts: [
      { name: 'Noto Sans Telugu', style: 'Text' },
      { name: 'Noto Serif Telugu', style: 'Text' },
      { name: 'Noto Sans Telugu UI', style: 'UI' },
      { name: 'Noto Serif Telugu UI', style: 'UI' },
      { name: 'Anek Telugu', style: 'Text' },
      { name: 'Baloo Tammudu 2', style: 'Display' },
      { name: 'Hind Guntur', style: 'Text' },
      { name: 'Gurajada', style: 'Text' },
      { name: 'Ramabhadra', style: 'Text' },
      { name: 'Mallanna', style: 'Text' },
      { name: 'Ponnala', style: 'Text' },
      { name: 'Timmana', style: 'Display' },
      { name: 'Suranna', style: 'Display' },
      { name: 'Vemana', style: 'Display' },
      { name: 'Sree Krushnadevaraya', style: 'Text' },
      { name: 'Tenali Ramakrishna', style: 'Text' },
      { name: 'Gidugu', style: 'Display' },
      { name: 'NTR', style: 'Display' },
      { name: 'Mandali', style: 'Handwriting' },
      { name: 'Lakki Reddy', style: 'Handwriting' },
      { name: 'Peddana', style: 'Text' },
      { name: 'Tiro Telugu', style: 'Text' },
      { name: 'Tiro Telugu Sanskrit', style: 'Traditional' },
      { name: 'Noto Sans Telugu Display', style: 'Display' },
      { name: 'Noto Serif Telugu Display', style: 'Display' }
    ]
  },
  hindi: {
    name: 'Hindi',
    script: 'Devanagari',
    tagline: 'Versatile Devanagari fonts crafted for Hindi content.',
    description: 'Browse Hindi fonts optimized for headlines, body text, and UI experiences.',
    sample: 'तेज़ भूरी लोमड़ी सुस्त कुत्ते पर कूदती है।',
    fonts: [
      { name: 'Noto Sans Devanagari', style: 'Text' },
      { name: 'Noto Serif Devanagari', style: 'Text' },
      { name: 'Noto Sans Devanagari UI', style: 'UI' },
      { name: 'Noto Serif Devanagari UI', style: 'UI' },
      { name: 'Anek Devanagari', style: 'Text' },
      { name: 'Hind', style: 'Text' },
      { name: 'Mukta', style: 'Text' },
      { name: 'Tiro Devanagari Hindi', style: 'Text' },
      { name: 'Tiro Devanagari Marathi', style: 'Text' },
      { name: 'Tiro Devanagari Sanskrit', style: 'Traditional' },
      { name: 'Martel', style: 'Text' },
      { name: 'Martel Sans', style: 'Text' },
      { name: 'Khand', style: 'Display' },
      { name: 'Kalam', style: 'Handwriting' },
      { name: 'Rajdhani', style: 'Display' },
      { name: 'Sahitya', style: 'Text' },
      { name: 'Sura', style: 'Text' },
      { name: 'Yatra One', style: 'Display' },
      { name: 'Baloo 2', style: 'Display' },
      { name: 'Baloo Bhaijaan 2', style: 'Display' },
      { name: 'Pragati Narrow', style: 'UI' },
      { name: 'Gotu', style: 'Text' },
      { name: 'Kadwa', style: 'Text' },
      { name: 'Teko', style: 'Display' },
      { name: 'Halant', style: 'Text' }
    ]
  },
  marathi: {
    name: 'Marathi',
    script: 'Devanagari',
    tagline: 'Marathi-friendly Devanagari fonts for publishing and UI.',
    description: 'Explore Marathi-ready fonts suited to editorial layouts and digital platforms.',
    sample: 'मराठीतला नमुना वाक्य येथे आहे.',
    fonts: [
      { name: 'Noto Sans Devanagari', style: 'Text' },
      { name: 'Noto Serif Devanagari', style: 'Text' },
      { name: 'Noto Sans Devanagari UI', style: 'UI' },
      { name: 'Noto Serif Devanagari UI', style: 'UI' },
      { name: 'Anek Devanagari', style: 'Text' },
      { name: 'Tiro Devanagari Marathi', style: 'Text' },
      { name: 'Tiro Devanagari Hindi', style: 'Text' },
      { name: 'Tiro Devanagari Sanskrit', style: 'Traditional' },
      { name: 'Hind', style: 'Text' },
      { name: 'Mukta', style: 'Text' },
      { name: 'Martel', style: 'Text' },
      { name: 'Martel Sans', style: 'Text' },
      { name: 'Khand', style: 'Display' },
      { name: 'Kalam', style: 'Handwriting' },
      { name: 'Rajdhani', style: 'Display' },
      { name: 'Sahitya', style: 'Text' },
      { name: 'Sura', style: 'Text' },
      { name: 'Yatra One', style: 'Display' },
      { name: 'Baloo 2', style: 'Display' },
      { name: 'Baloo Bhaijaan 2', style: 'Display' },
      { name: 'Pragati Narrow', style: 'UI' },
      { name: 'Gotu', style: 'Text' },
      { name: 'Kadwa', style: 'Text' },
      { name: 'Teko', style: 'Display' },
      { name: 'Halant', style: 'Text' }
    ]
  },
  tamil: {
    name: 'Tamil',
    script: 'Tamil',
    tagline: 'Tamil fonts for editorial, UI, and cultural storytelling.',
    description: 'Browse Tamil fonts that balance readability with expressive display styles.',
    sample: 'தமிழில் ஒரு மாதிரி வாக்கியம்.',
    fonts: [
      { name: 'Noto Sans Tamil', style: 'Text' },
      { name: 'Noto Serif Tamil', style: 'Text' },
      { name: 'Noto Sans Tamil UI', style: 'UI' },
      { name: 'Noto Serif Tamil UI', style: 'UI' },
      { name: 'Anek Tamil', style: 'Text' },
      { name: 'Baloo Thambi 2', style: 'Display' },
      { name: 'Hind Madurai', style: 'Text' },
      { name: 'Catamaran', style: 'Text' },
      { name: 'Kavivanar', style: 'Display' },
      { name: 'Mukta Malar', style: 'Text' },
      { name: 'Pavanam', style: 'Text' },
      { name: 'Arima Madurai', style: 'Display' },
      { name: 'Meera Inimai', style: 'Text' },
      { name: 'Tiro Tamil', style: 'Text' },
      { name: 'Tiro Tamil Sanskrit', style: 'Traditional' },
      { name: 'Noto Sans Tamil Supplement', style: 'Text' },
      { name: 'Noto Serif Tamil Supplement', style: 'Text' },
      { name: 'Noto Sans Tamil Display', style: 'Display' },
      { name: 'Noto Serif Tamil Display', style: 'Display' },
      { name: 'Noto Sans Tamil Rounded', style: 'Text' },
      { name: 'Noto Serif Tamil Rounded', style: 'Text' },
      { name: 'Noto Sans Tamil Traditional', style: 'Text' },
      { name: 'Noto Serif Tamil Traditional', style: 'Text' },
      { name: 'Tamil Sangam MN', style: 'Text' },
      { name: 'Tamil MN', style: 'Text' }
    ]
  },
  malayalam: {
    name: 'Malayalam',
    script: 'Malayalam',
    tagline: 'Malayalam fonts for UI, publishing, and cultural content.',
    description: 'A Malayalam collection emphasizing clarity for both print and digital.',
    sample: 'മലയാളത്തിൽ ഒരു മാതൃക വാക്യം.',
    fonts: [
      { name: 'Noto Sans Malayalam', style: 'Text' },
      { name: 'Noto Serif Malayalam', style: 'Text' },
      { name: 'Noto Sans Malayalam UI', style: 'UI' },
      { name: 'Noto Serif Malayalam UI', style: 'UI' },
      { name: 'Anek Malayalam', style: 'Text' },
      { name: 'Baloo Chettan 2', style: 'Display' },
      { name: 'Chilanka', style: 'Handwriting' },
      { name: 'Gayathri', style: 'Text' },
      { name: 'Manjari', style: 'Text' },
      { name: 'Rachana', style: 'Text' },
      { name: 'Meera', style: 'Text' },
      { name: 'Noto Sans Malayalam Supplement', style: 'Text' },
      { name: 'Noto Serif Malayalam Supplement', style: 'Text' },
      { name: 'Tiro Malayalam', style: 'Text' },
      { name: 'Tiro Malayalam Sanskrit', style: 'Traditional' },
      { name: 'AnjaliOldLipi', style: 'Traditional' },
      { name: 'Noto Sans Malayalam Display', style: 'Display' },
      { name: 'Noto Serif Malayalam Display', style: 'Display' },
      { name: 'Noto Sans Malayalam Rounded', style: 'Text' },
      { name: 'Noto Serif Malayalam Rounded', style: 'Text' },
      { name: 'Noto Sans Malayalam Traditional', style: 'Text' },
      { name: 'Noto Serif Malayalam Traditional', style: 'Text' },
      { name: 'Noto Sans Malayalam Hand', style: 'Handwriting' },
      { name: 'Noto Serif Malayalam Hand', style: 'Handwriting' },
      { name: 'Malayalam Sangam MN', style: 'Text' }
    ]
  },
  kannada: {
    name: 'Kannada',
    script: 'Kannada',
    tagline: 'Kannada typefaces for modern UI and long-form reading.',
    description: 'Browse Kannada fonts that work across headlines, body copy, and signage.',
    sample: 'ಕನ್ನಡದಲ್ಲಿ ಮಾದರಿ ವಾಕ್ಯ.',
    fonts: [
      { name: 'Noto Sans Kannada', style: 'Text' },
      { name: 'Noto Serif Kannada', style: 'Text' },
      { name: 'Noto Sans Kannada UI', style: 'UI' },
      { name: 'Noto Serif Kannada UI', style: 'UI' },
      { name: 'Anek Kannada', style: 'Text' },
      { name: 'Baloo Tamma 2', style: 'Display' },
      { name: 'Tiro Kannada', style: 'Text' },
      { name: 'Tiro Kannada Sanskrit', style: 'Traditional' },
      { name: 'Noto Sans Kannada Display', style: 'Display' },
      { name: 'Noto Serif Kannada Display', style: 'Display' },
      { name: 'Noto Sans Kannada Supplement', style: 'Text' },
      { name: 'Noto Serif Kannada Supplement', style: 'Text' },
      { name: 'Noto Sans Kannada Rounded', style: 'Text' },
      { name: 'Noto Serif Kannada Rounded', style: 'Text' },
      { name: 'Noto Sans Kannada Traditional', style: 'Text' },
      { name: 'Noto Serif Kannada Traditional', style: 'Text' },
      { name: 'Noto Sans Kannada Hand', style: 'Handwriting' },
      { name: 'Noto Serif Kannada Hand', style: 'Handwriting' },
      { name: 'Kannada Sangam MN', style: 'Text' },
      { name: 'Tunga', style: 'Text' },
      { name: 'Kedage', style: 'Text' },
      { name: 'Nudi', style: 'Text' },
      { name: 'Basava', style: 'Display' },
      { name: 'Karnataka Sangam MN', style: 'Text' },
      { name: 'Mallige', style: 'Display' }
    ]
  },
  punjabi: {
    name: 'Punjabi',
    script: 'Gurmukhi',
    tagline: 'Punjabi (Gurmukhi) fonts for web, UI, and display.',
    description: 'Explore Punjabi fonts with a balance of readability and expressive display styles.',
    sample: 'ਪੰਜਾਬੀ ਵਿੱਚ ਨਮੂਨਾ ਵਾਕ।',
    fonts: [
      { name: 'Noto Sans Gurmukhi', style: 'Text' },
      { name: 'Noto Serif Gurmukhi', style: 'Text' },
      { name: 'Noto Sans Gurmukhi UI', style: 'UI' },
      { name: 'Noto Serif Gurmukhi UI', style: 'UI' },
      { name: 'Anek Gurmukhi', style: 'Text' },
      { name: 'Baloo Paaji 2', style: 'Display' },
      { name: 'Mukta Mahee', style: 'Text' },
      { name: 'Tiro Gurmukhi', style: 'Text' },
      { name: 'Tiro Gurmukhi Sanskrit', style: 'Traditional' },
      { name: 'Noto Sans Gurmukhi Display', style: 'Display' },
      { name: 'Noto Serif Gurmukhi Display', style: 'Display' },
      { name: 'Noto Sans Gurmukhi Rounded', style: 'Text' },
      { name: 'Noto Serif Gurmukhi Rounded', style: 'Text' },
      { name: 'Noto Sans Gurmukhi Traditional', style: 'Text' },
      { name: 'Noto Serif Gurmukhi Traditional', style: 'Text' },
      { name: 'Noto Sans Gurmukhi Hand', style: 'Handwriting' },
      { name: 'Noto Serif Gurmukhi Hand', style: 'Handwriting' },
      { name: 'Gurmukhi MN', style: 'Text' },
      { name: 'Raavi', style: 'Text' },
      { name: 'Saab', style: 'Display' },
      { name: 'Kohinoor Punjabi', style: 'Text' },
      { name: 'Punjab MN', style: 'Text' },
      { name: 'Amrit Kurti', style: 'Display' },
      { name: 'Jhandi', style: 'Display' },
      { name: 'Langar', style: 'Display' }
    ]
  },
  gujarati: {
    name: 'Gujarati',
    script: 'Gujarati',
    tagline: 'Gujarati fonts for long-form reading and vibrant display.',
    description: 'Discover Gujarati fonts optimized for UI, publishing, and branding.',
    sample: 'ગુજરાતીમાં નમૂના વાક્ય.',
    fonts: [
      { name: 'Noto Sans Gujarati', style: 'Text' },
      { name: 'Noto Serif Gujarati', style: 'Text' },
      { name: 'Noto Sans Gujarati UI', style: 'UI' },
      { name: 'Noto Serif Gujarati UI', style: 'UI' },
      { name: 'Anek Gujarati', style: 'Text' },
      { name: 'Baloo Bhai 2', style: 'Display' },
      { name: 'Hind Vadodara', style: 'Text' },
      { name: 'Mukta Vaani', style: 'Text' },
      { name: 'Tiro Gujarati', style: 'Text' },
      { name: 'Tiro Gujarati Sanskrit', style: 'Traditional' },
      { name: 'Noto Sans Gujarati Display', style: 'Display' },
      { name: 'Noto Serif Gujarati Display', style: 'Display' },
      { name: 'Noto Sans Gujarati Rounded', style: 'Text' },
      { name: 'Noto Serif Gujarati Rounded', style: 'Text' },
      { name: 'Noto Sans Gujarati Hand', style: 'Handwriting' },
      { name: 'Noto Serif Gujarati Hand', style: 'Handwriting' },
      { name: 'Noto Sans Gujarati Book', style: 'Text' },
      { name: 'Noto Serif Gujarati Book', style: 'Text' },
      { name: 'Noto Sans Gujarati Traditional', style: 'Text' },
      { name: 'Noto Serif Gujarati Traditional', style: 'Text' },
      { name: 'Gujarati Sangam MN', style: 'Text' },
      { name: 'Shruti', style: 'Text' },
      { name: 'Kohinoor Gujarati', style: 'Text' },
      { name: 'Rasa Gujarati', style: 'Display' },
      { name: 'Rekha', style: 'Display' }
    ]
  },
  odia: {
    name: 'Odia',
    script: 'Odia',
    tagline: 'Odia fonts built for legibility and expressive display.',
    description: 'Explore Odia fonts with text and decorative styles for digital and print.',
    sample: 'ଓଡ଼ିଆରେ ଏକ ନମୁନା ବାକ୍ୟ।',
    fonts: [
      { name: 'Noto Sans Oriya', style: 'Text' },
      { name: 'Noto Serif Oriya', style: 'Text' },
      { name: 'Noto Sans Oriya UI', style: 'UI' },
      { name: 'Noto Serif Oriya UI', style: 'UI' },
      { name: 'Anek Odia', style: 'Text' },
      { name: 'Baloo Bhaina 2', style: 'Display' },
      { name: 'Tiro Odia', style: 'Text' },
      { name: 'Tiro Odia Sanskrit', style: 'Traditional' },
      { name: 'Noto Sans Oriya Display', style: 'Display' },
      { name: 'Noto Serif Oriya Display', style: 'Display' },
      { name: 'Noto Sans Oriya Rounded', style: 'Text' },
      { name: 'Noto Serif Oriya Rounded', style: 'Text' },
      { name: 'Noto Sans Oriya Hand', style: 'Handwriting' },
      { name: 'Noto Serif Oriya Hand', style: 'Handwriting' },
      { name: 'Noto Sans Oriya Traditional', style: 'Text' },
      { name: 'Noto Serif Oriya Traditional', style: 'Text' },
      { name: 'Kalinga', style: 'Text' },
      { name: 'Odia Sangam MN', style: 'Text' },
      { name: 'Utkal', style: 'Display' },
      { name: 'Odia MN', style: 'Text' },
      { name: 'Konark', style: 'Display' },
      { name: 'Shreya', style: 'Text' },
      { name: 'Chilika', style: 'Display' },
      { name: 'Kalinga Script', style: 'Handwriting' },
      { name: 'Noto Sans Oriya Book', style: 'Text' }
    ]
  },
  bengali: {
    name: 'Bengali',
    script: 'Bangla',
    tagline: 'Bengali fonts for publishing, branding, and UI.',
    description: 'Browse Bengali typefaces that support both modern layouts and traditional forms.',
    sample: 'বাংলায় একটি নমুনা বাক্য।',
    fonts: [
      { name: 'Noto Sans Bengali', style: 'Text' },
      { name: 'Noto Serif Bengali', style: 'Text' },
      { name: 'Noto Sans Bengali UI', style: 'UI' },
      { name: 'Noto Serif Bengali UI', style: 'UI' },
      { name: 'Anek Bangla', style: 'Text' },
      { name: 'Baloo Da 2', style: 'Display' },
      { name: 'Hind Siliguri', style: 'Text' },
      { name: 'Mukta', style: 'Text' },
      { name: 'Tiro Bangla', style: 'Text' },
      { name: 'Tiro Bangla Sanskrit', style: 'Traditional' },
      { name: 'Atma', style: 'Display' },
      { name: 'Noto Sans Bengali Display', style: 'Display' },
      { name: 'Noto Serif Bengali Display', style: 'Display' },
      { name: 'Noto Sans Bengali Rounded', style: 'Text' },
      { name: 'Noto Serif Bengali Rounded', style: 'Text' },
      { name: 'Noto Sans Bengali Hand', style: 'Handwriting' },
      { name: 'Noto Serif Bengali Hand', style: 'Handwriting' },
      { name: 'Noto Sans Bengali Traditional', style: 'Text' },
      { name: 'Noto Serif Bengali Traditional', style: 'Text' },
      { name: 'Bangla Sangam MN', style: 'Text' },
      { name: 'Kohinoor Bangla', style: 'Text' },
      { name: 'Siyam Rupali', style: 'Text' },
      { name: 'Ruposhi Bangla', style: 'Text' },
      { name: 'SutonnyMJ', style: 'Display' },
      { name: 'Rupali', style: 'Display' }
    ]
  },
  urdu: {
    name: 'Urdu',
    script: 'Arabic',
    tagline: 'Elegant Urdu fonts for Nastaliq and Naskh styles.',
    description: 'Explore Urdu-ready fonts with calligraphic flair and UI-friendly styles.',
    sample: 'یہ اردو میں ایک نمونہ جملہ ہے۔',
    fonts: [
      { name: 'Noto Naskh Arabic', style: 'Text' },
      { name: 'Noto Nastaliq Urdu', style: 'Traditional' },
      { name: 'Noto Sans Arabic', style: 'Text' },
      { name: 'Noto Sans Arabic UI', style: 'UI' },
      { name: 'Noto Naskh Arabic UI', style: 'UI' },
      { name: 'Noto Kufi Arabic', style: 'Display' },
      { name: 'Amiri', style: 'Traditional' },
      { name: 'Scheherazade New', style: 'Traditional' },
      { name: 'Lateef', style: 'Traditional' },
      { name: 'Reem Kufi', style: 'Display' },
      { name: 'Cairo', style: 'Text' },
      { name: 'Changa', style: 'Display' },
      { name: 'El Messiri', style: 'Text' },
      { name: 'Harmattan', style: 'Text' },
      { name: 'Markazi Text', style: 'Text' },
      { name: 'Mirza', style: 'Traditional' },
      { name: 'Rakkas', style: 'Display' },
      { name: 'Tajawal', style: 'Text' },
      { name: 'Mada', style: 'Text' },
      { name: 'Almarai', style: 'Text' },
      { name: 'Baloo Bhaijaan 2', style: 'Display' },
      { name: 'Jomhuria', style: 'Display' },
      { name: 'Katibeh', style: 'Display' },
      { name: 'Lalezar', style: 'Display' },
      { name: 'Vibes', style: 'Display' }
    ]
  },
  assamese: {
    name: 'Assamese',
    script: 'Bangla',
    tagline: 'Assamese-ready Bangla script fonts for digital and print.',
    description: 'Explore Assamese-supporting fonts with clean text styles and expressive displays.',
    sample: 'অসমীয়াত এটা নমুনা বাক্য।',
    fonts: [
      { name: 'Noto Sans Bengali', style: 'Text' },
      { name: 'Noto Serif Bengali', style: 'Text' },
      { name: 'Noto Sans Bengali UI', style: 'UI' },
      { name: 'Noto Serif Bengali UI', style: 'UI' },
      { name: 'Anek Bangla', style: 'Text' },
      { name: 'Baloo Da 2', style: 'Display' },
      { name: 'Hind Siliguri', style: 'Text' },
      { name: 'Mukta', style: 'Text' },
      { name: 'Tiro Bangla', style: 'Text' },
      { name: 'Tiro Bangla Sanskrit', style: 'Traditional' },
      { name: 'Atma', style: 'Display' },
      { name: 'Noto Sans Bengali Display', style: 'Display' },
      { name: 'Noto Serif Bengali Display', style: 'Display' },
      { name: 'Noto Sans Bengali Rounded', style: 'Text' },
      { name: 'Noto Serif Bengali Rounded', style: 'Text' },
      { name: 'Noto Sans Bengali Traditional', style: 'Text' },
      { name: 'Noto Serif Bengali Traditional', style: 'Text' },
      { name: 'Bangla Sangam MN', style: 'Text' },
      { name: 'Kohinoor Bangla', style: 'Text' },
      { name: 'Siyam Rupali', style: 'Text' },
      { name: 'Ruposhi Bangla', style: 'Text' },
      { name: 'Noto Sans Assamese', style: 'Text' },
      { name: 'Noto Serif Assamese', style: 'Text' },
      { name: 'Assamese MN', style: 'Text' },
      { name: 'Assam Script', style: 'Display' }
    ]
  }
};
